apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.mad.service: db-keycloak-service
  name: db-keycloak-service
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.mad.service: db-keycloak-service
status:
  loadBalancer: {}
