apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.webapp.entrypoints: web
    traefik.http.routers.webapp.rule: Host(`app.mad.localhost`)
    traefik.http.services.webapp.loadbalancer.server.port: "80"
  creationTimestamp: null
  labels:
    io.mad.service: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: webapp
  strategy: {}
  template:
    metadata:
      annotations:
        traefik.enable: "true"
        traefik.http.routers.webapp.entrypoints: web
        traefik.http.routers.webapp.rule: Host(`app.mad.localhost`)
        traefik.http.services.webapp.loadbalancer.server.port: "80"
      creationTimestamp: null
      labels:
        io.mad.network/mad-network: "true"
        io.mad.service: webapp
    spec:
      containers:
        - env:
            - name: VITE_DOCS_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_DOCS_BASE_URL
                  name: env-webapp
            - name: VITE_GOAT4SHELL_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_GOAT4SHELL_BASE_URL
                  name: env-webapp
            - name: VITE_KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: VITE_KEYCLOAK_CLIENT_ID
                  name: env-webapp
            - name: VITE_KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  key: VITE_KEYCLOAK_REALM
                  name: env-webapp
            - name: VITE_KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_KEYCLOAK_URL
                  name: env-webapp
            - name: VITE_LESSON_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_LESSON_BASE_URL
                  name: env-webapp
            - name: VITE_SCOREBOARD_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_SCOREBOARD_BASE_URL
                  name: env-webapp
          image: ghcr.io/mad-goat-project/mad-web-app:main
          name: mad-web-app
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
            requests:
              cpu: 250m
              memory: "268435456"
      restartPolicy: Always
status: {}
