apiVersion: v1
kind: Service
metadata:
  annotations:

  creationTimestamp: null
  labels:
    io.mad.service: db-lesson-service
  name: db-lesson-service
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.mad.service: db-lesson-service
status:
  loadBalancer: {}
