apiVersion: v1
kind: Service
metadata:
  annotations:

  creationTimestamp: null
  labels:
    io.mad.service: db-scoreboard-service
  name: db-scoreboard-service
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.mad.service: db-scoreboard-service
status:
  loadBalancer: {}
